# Generated by Django 4.0.5 on 2022-06-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_don', models.AutoField(primary_key=True, serialize=False, verbose_name='Id organización')),
                ('nombre_donacion', models.CharField(max_length=50, verbose_name='nombre organización')),
                ('description_1_donacion', models.CharField(max_length=50, verbose_name='descripción simple')),
                ('description_2_donacion', models.CharField(max_length=350, verbose_name='descripción detallada')),
                ('img_dir_donacion', models.CharField(max_length=50, verbose_name='imagen fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_form', models.AutoField(primary_key=True, serialize=False, verbose_name='correlativo form')),
                ('nombre_form', models.CharField(max_length=50, verbose_name='nombre form')),
                ('apellidos_form', models.CharField(max_length=50, verbose_name='apellidos form')),
                ('fono_form', models.CharField(max_length=12, verbose_name='fono form')),
                ('email_form', models.CharField(max_length=50, verbose_name='mail form')),
                ('region_form', models.CharField(max_length=50, verbose_name='region form')),
                ('comuna_form', models.CharField(max_length=50, verbose_name='comuna form')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_prod',
            field=models.CharField(max_length=50, verbose_name='Tipo Mascota'),
        ),
    ]
