# Generated by Django 4.0.5 on 2022-06-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donacion_formulario_alter_producto_tipo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_prod',
            field=models.CharField(max_length=1000, verbose_name='Descripción de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=200, verbose_name='Nombre producto'),
        ),
    ]
