# Generated by Django 4.0.5 on 2022-06-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descripcion_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='description_1_donacion',
            field=models.CharField(max_length=500, verbose_name='descripción simple'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='description_2_donacion',
            field=models.CharField(max_length=550, verbose_name='descripción detallada'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='img_dir_donacion',
            field=models.CharField(max_length=2000, verbose_name='imagen fundación'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='nombre_donacion',
            field=models.CharField(max_length=100, verbose_name='nombre organización'),
        ),
    ]
