# Generated by Django 4.0.5 on 2022-07-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donacion_description_1_donacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='correlativo form')),
                ('id_venta', models.IntegerField(verbose_name='Venta asociada')),
                ('producto', models.IntegerField(verbose_name='Valor producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad comprada')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='correlativo venta')),
                ('user', models.CharField(max_length=50, verbose_name='user comprador')),
                ('total', models.IntegerField(verbose_name='Valor Total venta')),
            ],
        ),
    ]
