# Generated by Django 4.0.5 on 2022-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_detalle_venta_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Valor Total venta'),
        ),
    ]
